routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Route::get('/home', function () {
//    if (session('status')) {
//        return redirect()->route('admin.home')->with('status', session('status'));
//    }
//
//    return redirect()->route('admin.home');
//});

Route::get('/', function () {
    return redirect()->route('admin.tasks.index');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('permissions', 'PermissionsController');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    Route::delete('tasks/destroy', 'TasksController@massDestroy')->name('tasks.massDestroy');
    Route::patch('tasks/approved/{task}', 'TasksController@approved')->name('tasks.approved');
    Route::get('/tasks/marketica', 'TasksController@observeMarketica')->name('tasks.marketica');
    Route::resource('tasks', 'TasksController');

    Route::get('archive/tasks', 'ArchiveTaskController@index')->name('archive.tasks.index');

    Route::get('archive/tasks/{task}', 'ArchiveTaskController@restore')->name('archive.tasks.restore');
    Route::get('archive/deleted-tasks/{id?}', 'ArchiveTaskController@show')->name('archive.tasks.show');
    Route::delete('archive/tasks/{task}', 'ArchiveTaskController@destroy')->name('archive.tasks.destroy');
    Route::get('archive/tasks/destroy', 'ArchiveTaskController@massDestroy')->name('archive.tasks.massDestroy');

    Route::resource('projects', 'ProjectsController');

    Route::resource('tasks.comments', 'TaskCommentsController')->only('store')->shallow();
});

/*
 * сделать сменить вкладку сменить пароль для пользователей
 * */
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

Route::post('telegram/webhook', 'Telegram\TelegramController@webhookHandler')->name('webhook');
Route::get('telegram/setWebhook', 'Telegram\TelegramController@setWebhook')->name('webhook');


Route::get('telegram/push-message', 'Telegram\TelegramPushMessageController@pushMessageForAllUsers');

//Route::get('test', 'TestController@test');

// files
Route::post('dropzone/add/{id}', 'Admin\MediaTaskController@store');
Route::post("media-task/destroy", 'Admin\MediaTaskController@destroy');

Route::middleware('auth')->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

resources/views/partials/breadcrumbs.blade.php
@if (count($breadcrumbs))

    <ol class="breadcrumb border-0 m-0 px-0 px-md-3">
        @foreach ($breadcrumbs as $breadcrumb)

            @if ($breadcrumb->url && !$loop->last)
                <li class="breadcrumb-item"><a href="{{ $breadcrumb->url }}">{{ $breadcrumb->title }}</a></li>
            @else
                <li class="breadcrumb-item active">{{ $breadcrumb->title }}</li>
            @endif

        @endforeach
    </ol>

@endif

resources/views/partials/flash.blade.php
@if(session('message'))
    <div class="row mb-2">
        <div class="col-lg-12">
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{ session('message') }}
                <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
        </div>
    </div>
@endif
@if(session('info'))
    <div class="row mb-2">
        <div class="col-lg-12">
            <div class="alert alert-info alert-dismissible fade show" role="alert">
                {{ session('info') }}
                <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
            </div>
        </div>
    </div>
@endif
@if($errors->count() > 0)
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <ul class="list-unstyled">
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
        <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
    </div>
@endif

resources/views/partials/menu.blade.php
<div id="sidebar" class="c-sidebar c-sidebar-fixed c-sidebar-lg-show">

    <div class="c-sidebar-brand d-md-down-none">
        <a class="c-sidebar-brand-full h4" href="#">
            {{ trans('panel.site_title') }}
        </a>
    </div>

    <ul class="c-sidebar-nav">
{{--        <li class="c-sidebar-nav-item">--}}
{{--            <a href="{{ route("admin.home") }}" class="c-sidebar-nav-link">--}}
{{--                <i class="c-sidebar-nav-icon fas fa-fw fa-tachometer-alt">--}}

{{--                </i>--}}
{{--                {{ trans('global.dashboard') }}--}}
{{--            </a>--}}
{{--        </li>--}}
        @can('task_management_access')
            <li class="c-sidebar-nav-dropdown {{ request()->is("admin/tasks") || request()->is("admin/tasks/*") ? "c-show" : "" }}">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="fa fa-tasks c-sidebar-nav-icon">

                    </i>
                    Заявки
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    @can('task_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.tasks.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/tasks") || request()->is("admin/tasks/*") ? "active" : "" }}">
                                <i class="fa fa-thumb-tack c-sidebar-nav-icon">

                                </i>
                               Активные заявки
                            </a>
                        </li>
                    @endcan
                    @can('task_marketica')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.tasks.marketica") }}" class="c-sidebar-nav-link {{ request()->is("admin/tasks") || request()->is("admin/tasks/*") ? "active" : "" }}">
                                <i class="fa fa-thumb-tack c-sidebar-nav-icon">

                                </i>
                               Задачи Маркетики
                            </a>
                        </li>
                    @endcan
                    @can('task_archive_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.archive.tasks.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/archive/tasks") || request()->is("admin/archive/tasks/*") ? "active" : "" }}">
                                <i class="fa fa-archive c-sidebar-nav-icon">

                                </i>
                                Архив заявок
                            </a>
                        </li>
                    @endcan
                    @can('task_create')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.tasks.create") }}" class="c-sidebar-nav-link {{ request()->is("admin/tasks/create") || request()->is("admin/tasks/create/*") ? "active" : "" }}">
                                <i class="fa fa-plus c-sidebar-nav-icon">

                                </i>
                                Создать заявку
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan
        @can('user_management_access')
            <li class="c-sidebar-nav-dropdown">
                <a class="c-sidebar-nav-dropdown-toggle" href="#">
                    <i class="fa-fw fas fa-users c-sidebar-nav-icon">

                    </i>
                    {{ trans('cruds.userManagement.title') }}
                </a>
                <ul class="c-sidebar-nav-dropdown-items">
                    @can('permission_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.permissions.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/permissions") || request()->is("admin/permissions/*") ? "active" : "" }}">
                                <i class="fa-fw fas fa-unlock-alt c-sidebar-nav-icon">

                                </i>
                                Разрешения
                            </a>
                        </li>
                    @endcan
                    @can('role_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.roles.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/roles") || request()->is("admin/roles/*") ? "active" : "" }}">
                                <i class="fa-fw fas fa-briefcase c-sidebar-nav-icon">

                                </i>
                                Роли
                            </a>
                        </li>
                    @endcan
                    @can('user_access')
                        <li class="c-sidebar-nav-item">
                            <a href="{{ route("admin.users.index") }}" class="c-sidebar-nav-link {{ request()->is("admin/users") || request()->is("admin/users/*") ? "active" : "" }}">
                                <i class="fa-fw fas fa-user c-sidebar-nav-icon">

                                </i>
                                Пользователи
                            </a>
                        </li>
                    @endcan
                </ul>
            </li>
        @endcan
        @can('project_management_access')
            <li class="c-sidebar-nav-item">
                <a class="c-sidebar-nav-link {{ request()->is('admin/projects') || request()->is('admin/projects/*') ? 'active' : '' }}" href="{{ route('admin.projects.index') }}">
                    <i class="fa fa-address-card c-sidebar-nav-icon">
                    </i>
                    Плательщики
                </a>
            </li>
        @endcan
        @if(file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php')))
            @can('profile_password_edit')
                <li class="c-sidebar-nav-item">
                    <a class="c-sidebar-nav-link {{ request()->is('profile/password') || request()->is('profile/password/*') ? 'active' : '' }}" href="{{ route('profile.password.edit') }}">
                        <i class="fa-fw fas fa-key c-sidebar-nav-icon">
                        </i>
                        Сменить пароль
                    </a>
                </li>
            @endcan
        @endif
        <li class="c-sidebar-nav-item">
            <a href="#" class="c-sidebar-nav-link" onclick="event.preventDefault(); document.getElementById('logoutform').submit();">
                <i class="c-sidebar-nav-icon fas fa-fw fa-sign-out-alt">

                </i>
                {{ trans('global.logout') }}
            </a>
        </li>
    </ul>

</div>