routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Route::get('/home', function () {
//    if (session('status')) {
//        return redirect()->route('admin.home')->with('status', session('status'));
//    }
//
//    return redirect()->route('admin.home');
//});

Route::get('/', function () {
    return redirect()->route('admin.tasks.index');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('permissions', 'PermissionsController');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    Route::delete('tasks/destroy', 'TasksController@massDestroy')->name('tasks.massDestroy');
    Route::patch('tasks/approved/{task}', 'TasksController@approved')->name('tasks.approved');
    Route::get('/tasks/marketica', 'TasksController@observeMarketica')->name('tasks.marketica');
    Route::resource('tasks', 'TasksController');

    Route::get('archive/tasks', 'ArchiveTaskController@index')->name('archive.tasks.index');

    Route::get('archive/tasks/{task}', 'ArchiveTaskController@restore')->name('archive.tasks.restore');
    Route::get('archive/deleted-tasks/{id?}', 'ArchiveTaskController@show')->name('archive.tasks.show');
    Route::delete('archive/tasks/{task}', 'ArchiveTaskController@destroy')->name('archive.tasks.destroy');
    Route::get('archive/tasks/destroy', 'ArchiveTaskController@massDestroy')->name('archive.tasks.massDestroy');

    Route::resource('projects', 'ProjectsController');

    Route::resource('tasks.comments', 'TaskCommentsController')->only('store')->shallow();
});

/*
 * сделать сменить вкладку сменить пароль для пользователей
 * */
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

Route::post('telegram/webhook', 'Telegram\TelegramController@webhookHandler')->name('webhook');
Route::get('telegram/setWebhook', 'Telegram\TelegramController@setWebhook')->name('webhook');


Route::get('telegram/push-message', 'Telegram\TelegramPushMessageController@pushMessageForAllUsers');

//Route::get('test', 'TestController@test');

// files
Route::post('dropzone/add/{id}', 'Admin\MediaTaskController@store');
Route::post("media-task/destroy", 'Admin\MediaTaskController@destroy');

Route::middleware('auth')->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * App\Models\Task
 *
 * @property int $id
 * @property string $title
 * @property string $raw_body
 * @property string $body
 * @property string|null $deadline
 * @property int|null $project_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property string|null $file
 * @property string|null $original_file
 * @property string $contragent
 * @property \App\Models\Project|null $project
 * @property string $price
 * @property string $appointment
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\TaskComment[] $comments
 * @property-read int|null $comments_count
 * @property-read mixed $is_approved
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $observers
 * @property-read int|null $observers_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $owner
 * @property-read int|null $owner_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $responsible
 * @property-read int|null $responsible_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $users
 * @property-read int|null $users_count
 * @method static \Illuminate\Database\Eloquent\Builder|Task newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Task newQuery()
 * @method static \Illuminate\Database\Query\Builder|Task onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Task query()
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereAppointment($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereContragent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereDeadline($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereFile($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereOriginalFile($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereProject($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereProjectId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereRawBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Task withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Task withoutTrashed()
 * @mixin \Eloquent
 */
class Task extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function getIsApprovedAttribute()
    {
        return $this->observers()->wherePivot('user_id', '=', Auth::id())->wherePivot('task_id', '=', $this->id)->first()->pivot->is_approved;
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved');
    }

    public function owner()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=', Position::POSITION_OWNER);
    }

    public function responsible()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=',Position::POSITION_RESPONSIBLE);

    }

    public function observers()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=', Position::POSITION_OBSERVER);
    }

    public function comments()
    {
        return $this->hasMany(TaskComment::class);
    }

    public function project()
    {
        return $this->hasOne(Project::class, 'id', 'project_id');
    }
}

app/Http/Controllers/Admin/TasksController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\CreateTaskEvent;
use App\Events\UpdateTaskEvent;
use App\Http\Requests\MassDestroyTaskRequest;
use App\Http\Requests\StoreTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Models\Project;
use App\Models\Task;
use App\Models\TaskMedia;
use App\Models\User;
use App\Services\TaskService;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Gate;

class TasksController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tasks = Auth::user()->tasks()->with(['observers', 'owner', 'responsible'])->distinct()->get()->unique();

        return view('admin.tasks.index', compact('tasks'));
    }

    /**
     * Отображение заявок маркетики
     * */
    public function observeMarketica()
    {
        abort_if(Gate::denies('task_marketica'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tasks = Task::with(['observers', 'owner', 'responsible'])
            ->where('contragent', '=', 'Маркетика')
            ->orWhere('project', '=', 'Маркетика')
            ->distinct()
            ->get()
            ->unique();

        return view('admin.tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        abort_if(Gate::denies('task_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $task = new Task();
        $users = User::all();

        $projects = Project::all();
        return view('admin.tasks.create', compact('users', 'task', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreTaskRequest $request
     * @return RedirectResponse
     */
    public function store(StoreTaskRequest $request)
    {
        if ($request->hasFile('file')) {
            $pathToFile = $request->file('file')->store('uploads/tasks', 'public');
            $originalName = $request->file('file')->getClientOriginalName();
        } else {
            $pathToFile = null;
            $originalName = null;
        }

        $task = TaskService::addTask($request, $pathToFile, $originalName);

        event(new CreateTaskEvent($task));

        $request->session()->flash('message', 'Задача успешно создана!');

        return redirect()
            ->route('admin.tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        abort_if(Gate::denies('task_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $task = Task::findOrFail($id);
        $taskMedia = TaskMedia::getMedia($id);

        return view('admin.tasks.show', compact('task', 'taskMedia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Task $task
     * @return Application|Factory|Response|View
     */
    public function edit(Task $task)
    {
        abort_if(Gate::denies('task_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('name', 'id');
        $taskMedia = TaskMedia::getMedia($task->id);

        return view('admin.tasks.edit', compact('users', 'task', 'taskMedia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateTaskRequest $request
     * @param Task $task
     * @return RedirectResponse
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        if (TasksController::isApprovedTask($task)) {
            event(new UpdateTaskEvent($task));
        }


        if ($request->hasFile('file')) {
            Storage::disk('public')->delete($task->file);
            $pathToFile = $request->file('file')->store('uploads/tasks', 'public');
            $originalName = $request->file('file')->getClientOriginalName();
        } else {
            $pathToFile = $task->file;
            $originalName = $task->original_file;
        }

        TaskService::updateTask($request, $task, $pathToFile, $originalName);


        session()->flash('message', 'Задача успешно обновлена!');

        return redirect()
            ->route('admin.tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Task $task
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Task $task)
    {
        abort_if(Gate::denies('task_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $task->delete();

        return redirect()->route('admin.tasks.index');
    }

    public function approved(Task $task)
    {
        TaskService::approvedTask($task);

        session()->flash('message', 'Заявка успешно согласована');
        return redirect()->route('admin.tasks.show', compact('task'));
    }

    public function massDestroy(MassDestroyTaskRequest $request)
    {
        Task::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }


    public static function isApprovedTask($task) : bool
    {

        $responsibleCount = $task->observers()->count();
        $approvedCount = $task->observers()->wherePivot('is_approved', '=', true)->count();

        return $approvedCount == $responsibleCount;
    }
}

resources/views/admin/tasks/archive/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="card">
        <div class="card-header">
            Список архивных задач
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class=" table table-bordered table-striped table-hover datatable datatable-User">
                    <thead>
                    <tr>
                        <th></th>

                        <th>Плательщик</th>
                        <th>Контрагент</th>
                        <th>Сумма</th>
                        <th>Назначение</th>
                        <th>Постановщик</th>
                        <th>Ответственные</th>
                        <th> Дата окончания</th>
                        <th>Дата создания</th>
                        <th>Дата Закрытия</th>
                        <th>Согласовано</th>

                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($tasks as $key => $task)
                        <tr data-entry-id="{{ $task->id }}">
                            <td></td>

                            <td>
                                {{ $task->project ?? '' }}
                            </td>

                            <td>
                                {{ $task->contragent ?? '' }}
                            </td>
                            <td>
                                {{ $task->price ?? '' }}
                            </td>
                            <td>
                                {{ $task->appointment ?? '' }}
                            </td>


                            <td>
                                @foreach($task->owner as $owner)
                                    <span class="badge badge-info">{{ $owner->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                @foreach($task->responsible as $responsible)
                                    <span class="badge badge-info">{{ $responsible->name }}</span>
                                @endforeach
                            </td>
                            <td>
                                {{ $task->deadline }}
                            </td>
                            <td>
                                {{ $task->created_at }}
                            </td>
                            <td>
                                {{ $task->deleted_at }}
                            </td>
                            <td>
                                @foreach($task->observers as $observer)
                                    @if($observer->pivot->is_approved)
                                        <span class="badge badge-success">{{ $observer->name }}</span>
                                    @else
                                        <span class="badge badge-danger">{{ $observer->name }}</span>
                                    @endif
                                @endforeach
                            </td>
                            <td>
                                @can('task_restore')
                                    <a class="btn btn-xs btn-info"
                                       href="{{ route('admin.archive.tasks.restore', $task->id) }}">
                                        Восстановить
                                    </a>
                                @endcan

                                @can('task_show')
                                    <a class="btn btn-xs btn-primary"
                                       href="{{ route('admin.archive.tasks.show', $task->id) }}">
                                        {{ trans('global.view') }}
                                    </a>
                                @endcan

                                @can('task_force_delete')
                                    <form action="{{ route('admin.archive.tasks.destroy', $task->id) }}" method="POST"
                                          onsubmit="return confirm('Вы уверены?');" style="display: inline-block;">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="submit" class="btn btn-xs btn-danger"
                                               value="{{ trans('global.delete') }}">
                                    </form>
                                @endcan

                            </td>
                            <td>

                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>



@endsection
@section('scripts')
    @parent
    <script>
        $(function () {
            let dtButtons = $.extend(true, [], $.fn.dataTable.defaults.buttons)
            @can('task_delete')
            {{--let deleteButtonTrans = '{{ trans('global.datatables.delete') }}'--}}
            {{--let deleteButton = {--}}
            {{--    text: deleteButtonTrans,--}}
            {{--    url: "{{ route('admin.archive.tasks.massDestroy') }}",--}}
            {{--    className: 'btn-danger',--}}
            {{--    action: function (e, dt, node, config) {--}}
            {{--        var ids = $.map(dt.rows({ selected: true }).nodes(), function (entry) {--}}
            {{--            return $(entry).data('entry-id')--}}
            {{--        });--}}

            {{--        if (ids.length === 0) {--}}
            {{--            alert('{{ trans('global.datatables.zero_selected') }}')--}}

            {{--            return--}}
            {{--        }--}}

            {{--        if (confirm('{{ trans('global.areYouSure') }}')) {--}}
            {{--            $.ajax({--}}
            {{--                headers: {'x-csrf-token': _token},--}}
            {{--                method: 'POST',--}}
            {{--                url: config.url,--}}
            {{--                data: { ids: ids, _method: 'DELETE' }})--}}
            {{--                .done(function () { location.reload() })--}}
            {{--        }--}}
            {{--    }--}}
            {{--}--}}
            {{--dtButtons.push(deleteButton)--}}
            @endcan

            $.extend(true, $.fn.dataTable.defaults, {
                orderCellsTop: true,
                order: [[1, 'desc']],
                pageLength: 100,
            });
            let table = $('.datatable-User:not(.ajaxTable)').DataTable({buttons: dtButtons})
            $('a[data-toggle="tab"]').on('shown.bs.tab click', function (e) {
                $($.fn.dataTable.tables(true)).DataTable()
                    .columns.adjust();
            });

        })

    </script>
@endsection

resources/views/admin/tasks/archive/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="container-fluid">
        <div class="row">
            <a class="btn btn-default" href="{{ route('admin.archive.tasks.index') }}">
                Назад к списку
            </a>
            <div class="ml-auto">Постановщик: @foreach($task->owner as $key => $owner)
                    <span class="label label-info">{{ $owner->name }}</span>
                @endforeach</div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-header">
            <span>
                Просмотр заявки
            </span>

        </div>

        <div class="card-body">
            <div class="form-group">
                <div class="form-group">

                </div>
                <div class="card__title">
                    <h3>{{ $task->title }}</h3>
                </div>
                <hr>
                <div class="card__body">
                    {!! $task->body !!}
                </div>


                @if($task->file)
                    <div class="card__file">
                        <h6>Основной файл:</h6>
                        @if (Storage::disk('public')->has($task->file))
                            <a href="{{ config('app.url').'/storage/'.$task->file }}"
                               target="_blank">{{ $task->original_file }}</a>
                        @endif
                    </div>
                    <br>
                @endif


                @if(count($taskMedia) > 0)
                    <div class="card__file">
                        <h6>Дополнительные файлы:</h6>
                        @foreach($taskMedia as $media)
                            @if (Storage::disk('public')->has($media->path))
                                <a href="{{ config('app.url').'/storage/'.$media->path }}"
                                   target="_blank">{{ $media->original_name }}</a>
                                <br>
                            @endif
                        @endforeach
                    </div>
                @endif


                <br>
                @foreach($task->observers as $observer)
                    @if($observer->id == Auth::id() && !$task->is_approved)
                        <div class="card_approved">
                            <form action="{{ route('admin.archive.tasks.approved', $task->id) }}" method="POST">
                                @csrf
                                @method('PATCH')
                                <button class="btn btn-success width-250" type="submit">Согласовать</button>
                            </form>
                        </div>
                    @endif
                @endforeach
                <hr>
                @foreach($task->comments as $comment)
                    <div class="comment-wrapper mt-30">
                        <div class="card bg-light mb-3">
                            <div class="card-header"><span>{{ $comment->user->name }}</span> <small>{{ $comment->created_at }}</small></div>
                            <div class="card-body">
                                <p class="card-text">
                                    {!! $comment->body !!}
                                </p>
                            </div>
                        </div>
                    </div>
                @endforeach


                <br>
                <div class="card__responsible">
                    Ответственный:
                    @foreach($task->responsible as $key => $responsible)
                        <span class="label label-info">{{ $responsible->name }}</span>
                    @endforeach
                </div>
                <div class="card__deadline">
                    Дата окончания: {{ $task->deadline }}
                </div>

                <div class="card__delete">
                    @can('task_delete')
                        <form action="{{ route('admin.archive.tasks.destroy', $task->id) }}" method="POST" onsubmit="return confirm('{{ trans('global.areYouSure') }}');" style="display: inline-block;">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-xs btn-danger" value="Закрыть заявку">
                        </form>
                    @endcan
                </div>
            </div>
        </div>
    </div>
@endsection