routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

//Route::get('/home', function () {
//    if (session('status')) {
//        return redirect()->route('admin.home')->with('status', session('status'));
//    }
//
//    return redirect()->route('admin.home');
//});

Route::get('/', function () {
    return redirect()->route('admin.tasks.index');
});

Auth::routes(['register' => false]);

Route::group(['prefix' => 'admin', 'as' => 'admin.', 'namespace' => 'Admin', 'middleware' => ['auth']], function () {

    Route::get('/', 'HomeController@index')->name('home');

    Route::resource('permissions', 'PermissionsController');

    Route::resource('roles', 'RolesController');

    Route::delete('users/destroy', 'UsersController@massDestroy')->name('users.massDestroy');
    Route::resource('users', 'UsersController');

    Route::delete('tasks/destroy', 'TasksController@massDestroy')->name('tasks.massDestroy');
    Route::patch('tasks/approved/{task}', 'TasksController@approved')->name('tasks.approved');
    Route::get('/tasks/marketica', 'TasksController@observeMarketica')->name('tasks.marketica');
    Route::resource('tasks', 'TasksController');

    Route::get('archive/tasks', 'ArchiveTaskController@index')->name('archive.tasks.index');

    Route::get('archive/tasks/{task}', 'ArchiveTaskController@restore')->name('archive.tasks.restore');
    Route::get('archive/deleted-tasks/{id?}', 'ArchiveTaskController@show')->name('archive.tasks.show');
    Route::delete('archive/tasks/{task}', 'ArchiveTaskController@destroy')->name('archive.tasks.destroy');
    Route::get('archive/tasks/destroy', 'ArchiveTaskController@massDestroy')->name('archive.tasks.massDestroy');

    Route::resource('projects', 'ProjectsController');

    Route::resource('tasks.comments', 'TaskCommentsController')->only('store')->shallow();
});

/*
 * сделать сменить вкладку сменить пароль для пользователей
 * */
Route::group(['prefix' => 'profile', 'as' => 'profile.', 'namespace' => 'Auth', 'middleware' => ['auth']], function () {
    if (file_exists(app_path('Http/Controllers/Auth/ChangePasswordController.php'))) {
        Route::get('password', 'ChangePasswordController@edit')->name('password.edit');
        Route::post('password', 'ChangePasswordController@update')->name('password.update');
    }
});

Route::post('telegram/webhook', 'Telegram\TelegramController@webhookHandler')->name('webhook');
Route::get('telegram/setWebhook', 'Telegram\TelegramController@setWebhook')->name('webhook');


Route::get('telegram/push-message', 'Telegram\TelegramPushMessageController@pushMessageForAllUsers');

//Route::get('test', 'TestController@test');

// files
Route::post('dropzone/add/{id}', 'Admin\MediaTaskController@store');
Route::post("media-task/destroy", 'Admin\MediaTaskController@destroy');

Route::middleware('auth')->get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Task.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\Auth;
use Spatie\MediaLibrary\InteractsWithMedia;

/**
 * App\Models\Task
 *
 * @property int $id
 * @property string $title
 * @property string $raw_body
 * @property string $body
 * @property string|null $deadline
 * @property int|null $project_id
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @property \Illuminate\Support\Carbon|null $deleted_at
 * @property string|null $file
 * @property string|null $original_file
 * @property string $contragent
 * @property \App\Models\Project|null $project
 * @property string $price
 * @property string $appointment
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\TaskComment[] $comments
 * @property-read int|null $comments_count
 * @property-read mixed $is_approved
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $observers
 * @property-read int|null $observers_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $owner
 * @property-read int|null $owner_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $responsible
 * @property-read int|null $responsible_count
 * @property-read \Illuminate\Database\Eloquent\Collection|\App\Models\User[] $users
 * @property-read int|null $users_count
 * @method static \Illuminate\Database\Eloquent\Builder|Task newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|Task newQuery()
 * @method static \Illuminate\Database\Query\Builder|Task onlyTrashed()
 * @method static \Illuminate\Database\Eloquent\Builder|Task query()
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereAppointment($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereContragent($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereDeadline($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereFile($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereOriginalFile($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task wherePrice($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereProject($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereProjectId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereRawBody($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|Task whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|Task withTrashed()
 * @method static \Illuminate\Database\Query\Builder|Task withoutTrashed()
 * @mixin \Eloquent
 */
class Task extends Model
{
    use SoftDeletes;

    protected $guarded = [];

    public function getIsApprovedAttribute()
    {
        return $this->observers()->wherePivot('user_id', '=', Auth::id())->wherePivot('task_id', '=', $this->id)->first()->pivot->is_approved;
    }

    public function users()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved');
    }

    public function owner()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=', Position::POSITION_OWNER);
    }

    public function responsible()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=',Position::POSITION_RESPONSIBLE);

    }

    public function observers()
    {
        return $this->belongsToMany(User::class, 'user_task')
            ->withPivot('id', 'position_id', 'is_approved')
            ->wherePivot('position_id','=', Position::POSITION_OBSERVER);
    }

    public function comments()
    {
        return $this->hasMany(TaskComment::class);
    }

    public function project()
    {
        return $this->hasOne(Project::class, 'id', 'project_id');
    }
}

app/Http/Controllers/Admin/TasksController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Events\CreateTaskEvent;
use App\Events\UpdateTaskEvent;
use App\Http\Requests\MassDestroyTaskRequest;
use App\Http\Requests\StoreTaskRequest;
use App\Http\Requests\UpdateTaskRequest;
use App\Models\Project;
use App\Models\Task;
use App\Models\TaskMedia;
use App\Models\User;
use App\Services\TaskService;
use Exception;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;
use Illuminate\View\View;
use Gate;

class TasksController extends BaseController
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|Response|View
     */
    public function index()
    {
        abort_if(Gate::denies('task_access'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tasks = Auth::user()->tasks()->with(['observers', 'owner', 'responsible'])->distinct()->get()->unique();

        return view('admin.tasks.index', compact('tasks'));
    }

    /**
     * Отображение заявок маркетики
     * */
    public function observeMarketica()
    {
        abort_if(Gate::denies('task_marketica'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $tasks = Task::with(['observers', 'owner', 'responsible'])
            ->where('contragent', '=', 'Маркетика')
            ->orWhere('project', '=', 'Маркетика')
            ->distinct()
            ->get()
            ->unique();

        return view('admin.tasks.index', compact('tasks'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Application|Factory|Response|View
     */
    public function create()
    {
        abort_if(Gate::denies('task_create'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $task = new Task();
        $users = User::all();

        $projects = Project::all();
        return view('admin.tasks.create', compact('users', 'task', 'projects'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param StoreTaskRequest $request
     * @return RedirectResponse
     */
    public function store(StoreTaskRequest $request)
    {
        if ($request->hasFile('file')) {
            $pathToFile = $request->file('file')->store('uploads/tasks', 'public');
            $originalName = $request->file('file')->getClientOriginalName();
        } else {
            $pathToFile = null;
            $originalName = null;
        }

        $task = TaskService::addTask($request, $pathToFile, $originalName);

        event(new CreateTaskEvent($task));

        $request->session()->flash('message', 'Задача успешно создана!');

        return redirect()
            ->route('admin.tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Application|Factory|Response|View
     */
    public function show($id)
    {
        abort_if(Gate::denies('task_show'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $task = Task::findOrFail($id);
        $taskMedia = TaskMedia::getMedia($id);

        return view('admin.tasks.show', compact('task', 'taskMedia'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Task $task
     * @return Application|Factory|Response|View
     */
    public function edit(Task $task)
    {
        abort_if(Gate::denies('task_edit'), Response::HTTP_FORBIDDEN, '403 Forbidden');

        $users = User::all()->pluck('name', 'id');
        $taskMedia = TaskMedia::getMedia($task->id);

        return view('admin.tasks.edit', compact('users', 'task', 'taskMedia'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateTaskRequest $request
     * @param Task $task
     * @return RedirectResponse
     */
    public function update(UpdateTaskRequest $request, Task $task)
    {
        if (TasksController::isApprovedTask($task)) {
            event(new UpdateTaskEvent($task));
        }


        if ($request->hasFile('file')) {
            Storage::disk('public')->delete($task->file);
            $pathToFile = $request->file('file')->store('uploads/tasks', 'public');
            $originalName = $request->file('file')->getClientOriginalName();
        } else {
            $pathToFile = $task->file;
            $originalName = $task->original_file;
        }

        TaskService::updateTask($request, $task, $pathToFile, $originalName);


        session()->flash('message', 'Задача успешно обновлена!');

        return redirect()
            ->route('admin.tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Task $task
     * @return RedirectResponse
     * @throws Exception
     */
    public function destroy(Task $task)
    {
        abort_if(Gate::denies('task_delete'), Response::HTTP_FORBIDDEN, '403 Forbidden');
        $task->delete();

        return redirect()->route('admin.tasks.index');
    }

    public function approved(Task $task)
    {
        TaskService::approvedTask($task);

        session()->flash('message', 'Заявка успешно согласована');
        return redirect()->route('admin.tasks.show', compact('task'));
    }

    public function massDestroy(MassDestroyTaskRequest $request)
    {
        Task::whereIn('id', request('ids'))->delete();

        return response(null, Response::HTTP_NO_CONTENT);
    }


    public static function isApprovedTask($task) : bool
    {

        $responsibleCount = $task->observers()->count();
        $approvedCount = $task->observers()->wherePivot('is_approved', '=', true)->count();

        return $approvedCount == $responsibleCount;
    }
}

resources/views/admin/tasks/edit.blade.php
@extends('layouts.admin')

@section('content')
    <input hidden id="task-id" type="text" value="{{$task->id}}"/>

    <div class="card">
        <div class="card-header">
            Редактирование заявки
        </div>

        <div class="card-body">
            <form method="POST" action="{{ route("admin.tasks.update", $task->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="price">Сумма</label>
                        <input class="form-control {{ $errors->has('price') ? 'is-invalid' : '' }}" type="text"
                               name="price" id="price" value="{{ old('price', $task->price) }}">
                        @if($errors->has('price'))
                            <div class="invalid-feedback">
                                {{ $errors->first('price') }}
                            </div>
                        @endif
                    </div>


                    <div class="form-group col-md-3">
                        <label for="contragent">Контрагент</label>
                        <input class="form-control {{ $errors->has('contragent') ? 'is-invalid' : '' }}" type="text"
                               name="contragent" id="contragent" value="{{ old('contragent', $task->contragent) }}">
                        @if($errors->has('contragent'))
                            <div class="invalid-feedback">
                                {{ $errors->first('contragent') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group col-md-3">
                        <label for="appointment">Назначение</label>
                        <input class="form-control {{ $errors->has('appointment') ? 'is-invalid' : '' }}" type="text"
                               name="appointment" id="appointment" value="{{ old('appointment', $task->appointment) }}">
                        @if($errors->has('appointment'))
                            <div class="invalid-feedback">
                                {{ $errors->first('appointment') }}
                            </div>
                        @endif
                    </div>


                    <div class="form-group col-md-3">
                        <label for="deadline">Дата окончания заявки</label>
                        <input class="form-control {{ $errors->has('deadline') ? 'is-invalid' : '' }}"
                               value="{{ $task->deadline }}" type="date" name="deadline" id="deadline">
                        @if($errors->has('deadline'))
                            <div class="invalid-feedback">
                                {{ $errors->first('deadline') }}
                            </div>
                        @endif
                    </div>
                </div>

                <div class="form-group">
                    <label for="body">Описание заявки</label>
                    <textarea class="form-control {{ $errors->has('body') ? 'is-invalid' : '' }} body" type="body"
                              name="body" id="body">{{ old('body', $task->raw_body) }}</textarea>
                    @if($errors->has('body'))
                        <div class="invalid-feedback">
                            {{ $errors->first('body') }}
                        </div>
                    @endif
                </div>
                <div class="row">
                    <div class="form-group col-md-6">
                        <label for="observers">Наблюдатели</label>
                        <div style="padding-bottom: 4px">
                            <span class="btn btn-info btn-xs select-all"
                                  style="border-radius: 0">{{ trans('global.select_all') }}</span>
                            <span class="btn btn-info btn-xs deselect-all"
                                  style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                        </div>
                        <select class="form-control select2 {{ $errors->has('observers') ? 'is-invalid' : '' }}"
                                name="observers[]" id="observers" multiple>
                            @foreach($users as $id => $user)
                                <option
                                    value="{{ $id }}" {{ in_array($id, old('observers', $task->observers->pluck('id', 'id')->toArray())) ? 'selected' : '' }}>{{ $user }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('observers'))
                            <div class="invalid-feedback">
                                {{ $errors->first('observers') }}
                            </div>
                        @endif
                    </div>
                    <div class="form-group col-md-6">
                        <label for="responsible">Ответственные</label>
                        <div style="padding-bottom: 4px">
                            <span class="btn btn-info btn-xs select-all"
                                  style="border-radius: 0">{{ trans('global.select_all') }}</span>
                            <span class="btn btn-info btn-xs deselect-all"
                                  style="border-radius: 0">{{ trans('global.deselect_all') }}</span>
                        </div>
                        <select class="form-control select2 {{ $errors->has('responsible') ? 'is-invalid' : '' }}"
                                name="responsible[]" id="responsible" multiple>
                            @foreach($users as $id => $user)
                                <option
                                    value="{{ $id }}" {{ in_array($id, old('responsible', $task->responsible->pluck('id', 'id')->toArray())) ? 'selected' : '' }}>{{ $user }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('responsible'))
                            <div class="invalid-feedback">
                                {{ $errors->first('responsible') }}
                            </div>
                        @endif
                    </div>

                    <div class="form-group col-md-6">
                        <label for="responsible">Постановщик</label>

                        <select class="form-control {{ $errors->has('owner') ? 'is-invalid' : '' }}"
                                name="owner" id="owner">
                            @foreach($users as $id => $user)
                                <option
                                    value="{{ $id }}" {{ in_array($id, old('owner', $task->owner->pluck('id', 'id')->toArray())) ? 'selected' : '' }}>{{ $user }}</option>
                            @endforeach
                        </select>
                        @if($errors->has('owner'))
                            <div class="invalid-feedback">
                                {{ $errors->first('owner') }}
                            </div>
                        @endif
                    </div>


                </div>
                <a href="{{ config('app.url').'/storage/'.$task->file }}" target="_blank">Текущий файл</a>
                <div class="form-group">
                    <label class="required" for="title">Выберите новый файл если хотите его заменить</label>
                    <input class="form-control {{ $errors->has('file') ? 'is-invalid' : '' }}" type="file" name="file"
                           id="file" value="{{ old('file', '') }}">
                    @if($errors->has('file'))
                        <div class="invalid-feedback">
                            {{ $errors->first('file') }}
                        </div>
                    @endif
                </div>



                @if(count($taskMedia) > 0)
                    <div class="card__file">
                        <h6>Дополнительные файлы:</h6>
                        @foreach($taskMedia as $media)
                            @if (Storage::disk('public')->has($media->path))
                                <a href="{{ config('app.url').'/storage/'.$media->path }}"
                                   target="_blank">{{ $media->original_name }}</a>
                                <small class="badge badge-danger card__file--delete" data-id="{{ $media->id }}">Удалить файл</small>
                                <br>
                            @endif
                        @endforeach
                    </div>
                @endif

                <div class="form-group">
                    <label class="required" for="title">Добавьте файл</label>
                    <div class="dropzone">
                        <div class="fallback">
                            <input name="file" type="file" multiple/>
                        </div>
                    </div>

                </div>




                <div class="form-group">
                    <button class="btn btn-danger" id="save-task" type="submit">
                        {{ trans('global.save') }}
                    </button>
                </div>
            </form>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            Комментарии
        </div>
        <div class="card-body">
            <div class=" offset-md-2 col-md-8 mb-3">
                @foreach($task->comments as $comment)
                    <div class="comment-wrapper mt-30">
                        <div class="card bg-light mb-3">
                            <div class="card-header"><span>{{ $comment->user->name }}</span>
                                <small>{{ $comment->created_at }}</small></div>
                            <div class="card-body">
                                <p class="card-text">
                                    {!! $comment->body !!}
                                </p>
                            </div>
                        </div>
                    </div>
                @endforeach
                <hr>
                <form action="{{ route('admin.tasks.comments.store', $task->id) }}" method="POST">
                    @csrf
                    <div class="wpapp mb-3">
                        <textarea name="body" id="body" class="form-control comment"></textarea>

                    </div>
                    <button class="btn btn-info" type="submit">Оставить комментарий</button>
                </form>

            </div>
        </div>
    </div>


@endsection


@section('scripts')
    <script src="{{ asset('js/pages/tasks.js') }}"></script>
    <script src="{{ asset('js/pages/tasks-show.js') }}"></script>
@endsection

resources/views/admin/tasks/show.blade.php
@extends('layouts.admin')
@section('content')
    <input hidden id="task-id" type="text" value="{{$task->id}}"/>

    <div class="container-fluid">
        <div class="row">
            <a class="btn btn-default" href="{{ route('admin.tasks.index') }}">
                Назад к списку
            </a>
            <div class="ml-auto">Постановщик: @foreach($task->owner as $key => $owner)
                    <span class="label label-info">{{ $owner->name }}</span>
                @endforeach</div>
        </div>
    </div>
    <br>
    <div class="card">
        <div class="card-header">
            <span>
                Просмотр заявки
            </span>

        </div>

        <div class="card-body">
            <div class="form-group">
                <div class="form-group">

                </div>
                <div class="card__title">
                    <h3>{{ $task->title }}</h3>
                </div>
                <hr>
                <div class="card__body">
                    {!! $task->body !!}
                </div>

                @if($task->file)
                    <div class="card__file">
                        <h6>Основной файл:</h6>
                        @if (Storage::disk('public')->has($task->file))
                            <a href="{{ config('app.url').'/storage/'.$task->file }}"
                               target="_blank">{{ $task->original_file }}</a>
                        @endif
                    </div>
                    <br>
                @endif


                @if(count($taskMedia) > 0)
                    <div class="card__file">
                        <h6>Дополнительные файлы:</h6>
                        @foreach($taskMedia as $media)
                            @if (Storage::disk('public')->has($media->path))
                                <a href="{{ config('app.url').'/storage/'.$media->path }}"
                                   target="_blank">{{ $media->original_name }}</a>
                                <small class="badge badge-danger card__file--delete" data-id="{{ $media->id }}">Удалить файл</small>
                                <br>
                            @endif
                        @endforeach
                    </div>
                @endif

                <div class="form-group">
                    <label class="required" for="title">Добавьте файл</label>
                    <div class="dropzone">
                        <div class="fallback">
                            <input name="file" type="file" multiple/>
                        </div>
                    </div>

                </div>

                @foreach($task->observers as $observer)
                    @if($observer->id == Auth::id() && !$task->is_approved)
                        <div class="card_approved">
                            <form action="{{ route('admin.tasks.approved', $task->id) }}" method="POST">
                                @csrf
                                @method('PATCH')
                                <button class="btn btn-success width-250" type="submit">Согласовать</button>
                            </form>
                        </div>
                    @endif
                @endforeach
                <hr>
                @foreach($task->comments as $comment)
                    <div class="comment-wrapper mt-30">
                        <div class="card bg-light mb-3">
                            <div class="card-header"><span>{{ $comment->user->name }}</span>
                                <small>{{ $comment->created_at }}</small></div>
                            <div class="card-body">
                                <p class="card-text">
                                    {!! $comment->body !!}
                                </p>
                            </div>
                        </div>
                    </div>
                @endforeach

                <form action="{{ route('admin.tasks.comments.store', $task->id) }}" method="POST">
                    @csrf
                    <div class="wpapp mb-3">

                        <label for="exampleFormControlTextarea1">Комментарий</label>
                        <textarea class="form-control comment" name="body" id="body" rows="3"></textarea>

                    </div>
                    <button class="btn btn-info width-250" type="submit">Оставить комментарий</button>
                </form>
                <br>
                <div class="card__responsible">
                    Ответственный:
                    @foreach($task->responsible as $key => $responsible)
                        <span class="label label-info">{{ $responsible->name }}</span>
                    @endforeach
                </div>
                <div class="card__deadline">
                    Дата окончания: {{ $task->deadline }}
                </div>

                <div class="card__delete">
                    @can('task_delete')
                        <form action="{{ route('admin.tasks.destroy', $task->id) }}" method="POST"
                              onsubmit="return confirm('{{ trans('global.areYouSure') }}');"
                              style="display: inline-block;">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token() }}">
                            <input type="submit" class="btn btn-xs btn-danger" value="Закрыть заявку">
                        </form>
                    @endcan
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="{{ asset('js/pages/tasks-show.js') }}"></script>
@endsection